services:
  mysql:
    build:
      context: .
      dockerfile: mysqlDockerfile
    image: my-mysql:korean
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: foominity
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
#      - /etc/myapp/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    # ports: ["3306:3306"]  # 정말 필요할 때만 개방
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    mem_limit: 768m

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    env_file:
      - /home/ubuntu/Foominity/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "127.0.0.1:8084:8084"
    restart: always
    mem_limit: 512m

  frontend:
    build:
      context: .
      dockerfile: frontendDockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}


    container_name: frontend
    ports: ["127.0.0.1:3000:80"]
    restart: always

volumes:
  mysql_data: