spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  main:
    allow-bean-definition-overriding: true
  security:
    filter:
      order: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8084}
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_MS:3600000}
  refresh-token-validity: ${JWT_REFRESH_MS:3600000}

logging:
  level:
    org.springframework.security: ${SEC_LOG_LEVEL:DEBUG}

openai:
  api-key: ${OPENAI_API_KEY}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}