spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  main:
    allow-bean-definition-overriding: true
  security:
    filter:
      order: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    gcp:
      credentials:
        location: file:/etc/secrets/magazinetranslation-5dc5ba5ef0bd.json

server:
  port: ${SERVER_PORT:8084}
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_MS:3600000}
  refresh-token-validity: ${JWT_REFRESH_MS:3600000}

logging:
  level:
    org.springframework.security: ${SEC_LOG_LEVEL:DEBUG}

openai:
  api-key: ${OPENAI_API_KEY}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  api-base-url: https://api.spotify.com
  auth-url: https://accounts.spotify.com/api/token
  market: KR

rapidapi:
  key: ${RAPIDAPI_KEY}
  hosts:
    musixmatch: ${RAPIDAPI_HOST}

#  quiz:
#    duration-seconds: 30
#    hint-seconds: 15
#    round-ttl-seconds: 60
#    reveal-on-wrong: true #오답 시 정답 공개
#    filter:
#      allowed-genres: k-pop #, pop # 비워두면 모든 장르 허용
#      min-year: 1990 # **년도 이후 곡
#      max-year: 2050
#      exclude-explicit: true
#    oauth:
#      user-auth-enabled: true